source "https://rubygems.org"

gem "aws-sdk-ssm"
gem "csv"
gem "encrypted_credentials", github: "somleng/encrypted_credentials"
gem "faraday"
gem "rack"
gem "rate_center"
gem "stackprof"
gem "sentry-ruby"

group :development do
  gem "pry"
  gem "rspec"
  gem "rake"
  gem "rubocop"
  gem "rubocop-rails-omakase", require: false
  gem "rubocop-rspec"
  gem "rubocop-performance"
end

group :test do
  gem "webmock"
end
