version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: 'skyetel'
    schedule:
      interval: 'daily'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
