default: &default
  somleng_api_key: "<%= ENV['SOMLENG_API_KEY'] %>"
  skyetel_username: "<%= ENV['SKYETEL_USERNAME'] %>"
  skyetel_password: "<%= ENV['SKYETEL_PASSWORD'] %>"
  fibernetics_api_token: "<%= ENV['FIBERNETICS_API_TOKEN'] %>"
  supplier: "<%= ENV['SUPPLIER'] %>"
  supported_cities_data_file: "<%= ENV.fetch('SUPPORTED_CITIES_DATA_FILE', 'supported_cities.csv') %>"
  min_stock: "<%= ENV.fetch('MIN_STOCK', 0) %>"
  max_stock: "<%= ENV.fetch('MAX_STOCK', 0) %>"
  somleng_number_visibility: "<%= ENV.fetch('SOMLENG_NUMBER_VISIBILITY', 'public') %>"

development: &development
  <<: *default
  supported_cities_data_file: "supported_cities.sample.csv"
  supplier: "skyetel"

test:
  <<: *development

production: &production
  <<: *default
  sentry_dsn: "<%= ENV.fetch('SENTRY_DSN', 'https://f988ba7738e7fc213116567d026aa60e@o125014.ingest.us.sentry.io/4508059267366912') %>"

staging:
  <<: *production
