default: &default
  somleng_api_key: "<%= ENV['SOMLENG_API_KEY'] %>"
  skyetel_username: "<%= ENV['SKYETEL_USERNAME'] %>"
  skyetel_password: "<%= ENV['SKYETEL_PASSWORD'] %>"

development: &development
  <<: *default
  supported_cities_data_file: "supported_cities.sample.csv"

test:
  <<: *development

production: &production
  <<: *default
  sentry_dsn: "<%= ENV.fetch('SENTRY_DSN', 'https://f988ba7738e7fc213116567d026aa60e@o125014.ingest.us.sentry.io/4508059267366912') %>"

staging:
  <<: *production
