name: Inventory Manager

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        working-directory: inventory_manager
        bundler-cache: true

    - name: Run the tests
      run: bundle exec rake

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.SOMLENG_PERSONAL_ACCESS_TOKEN }}
