name: Update Data

on: push

defaults:
  run:
    working-directory: skyetel

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Update Data
        run: |
          ./lib/skyetel/bin/update_data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.SOMLENG_PERSONAL_ACCESS_TOKEN }}
          commit-message: "feat: Update data"
          title: "feat: Update data"
          labels: "update_data"
          base: "develop"
